/**
 * Categories/divisions are data-driven (DB) now, so these are plain string
 * aliases — the 5 built-in divisions are only the seeded defaults.
 */
export type CategoryType = string;

export type SubcategoryType = string;

export type BrandName = string;

/** A subcategory inside a division (Admin → Categories). */
export interface Subcategory {
  id: string;
  categoryId: string;
  name: string;
  nameBn?: string | null;
  slug: string;
  isActive: boolean;
  sortOrder: number;
}

/**
 * A storefront division / top-level category, loaded from `/api/categories`.
 * `slug` mirrors `Product.category` and `subcategories[].name` mirrors
 * `Product.subcategory`, which is what keeps catalog filtering working.
 */
export interface Category {
  id: string;
  name: string;
  nameBn?: string | null;
  slug: string;
  description: string;
  descriptionBn?: string | null;
  tagline: string;
  taglineBn?: string | null;
  brand: string;
  image?: string | null;
  heroImage?: string | null;
  gridImage?: string | null;
  badge: string;
  accentColor: string;
  isActive: boolean;
  sortOrder: number;
  subcategories: Subcategory[];
}

export interface ProductColor {
  name: string;
  hex: string;
  image: string;
}

export interface ProductSize {
  size: string;
  chestInches?: number;
  lengthInches?: number;
  waistInches?: number;
  eu?: number;
  uk?: number;
  us?: number;
  inStock: boolean;
  stockCount: number;
}

export interface Product {
  id: string;
  name: string;
  slug: string;
  brand: BrandName;
  category: CategoryType;
  subcategory: SubcategoryType | string;
  price: number;
  originalPrice?: number;
  discountPercent?: number;
  rating: number;
  reviewsCount: number;
  isNewArrival?: boolean;
  isBestSeller?: boolean;
  isTrending?: boolean;
  isClearance?: boolean;
  /** Admin flag — include this product in the homepage Featured section. */
  isFeatured?: boolean;
  featuredOrder?: number;
  description: string;
  features: string[];
  materials: {
    fabric: string;
    weave?: string;
    lining?: string;
    care: string;
    upper?: string;
    sole?: string;
    insole?: string;
  };
  fit?: 'Slim Fit' | 'Regular Fit' | 'Relaxed Fit' | 'Tailored Fit' | 'Classic Fit';
  pattern?: 'Solid' | 'Embroidered' | 'Printed' | 'Striped' | 'Checked' | 'Jacquard' | 'Textured';
  sleeve?: 'Full Sleeve' | 'Half Sleeve' | 'Three-Quarter' | 'Sleeveless';
  colors: ProductColor[];
  sizes: ProductSize[];
  images: string[];
  tags: string[];
  occasion: string;
  cushionTech?: string; // fabric tech or weave specialty
  sku: string;
}

export interface CartItem {
  cartItemId: string;
  product: Product;
  selectedColor: ProductColor;
  selectedSize: ProductSize;
  quantity: number;
  addedAt: number;
}

export interface WishlistItem {
  productId: string;
  product: Product;
  addedAt: number;
}

export interface FilterState {
  category: CategoryType;
  subcategory: string;
  brand: string[];
  priceRange: [number, number];
  sizes: (string | number)[];
  colors: string[];
  sortOption: 'featured' | 'bestseller' | 'price-low' | 'price-high' | 'rating' | 'newest';
  ratingMin: number;
  inStockOnly: boolean;
  onSaleOnly: boolean;
  searchQuery: string;
}

export interface Review {
  id: string;
  productId: string;
  author: string;
  city: string;
  rating: number;
  title: string;
  comment: string;
  date: string;
  verified: boolean;
  helpfulCount: number;
  fitFeedback?: 'runs_small' | 'true_to_size' | 'runs_large';
}

export interface StoreLocation {
  id: string;
  name: string;
  division: string;
  district: string;
  area: string;
  address: string;
  phone: string;
  openingHours: string;
  features: string[];
  lat: number;
  lng: number;
  isFlagship?: boolean;
}

export interface Coupon {
  code: string;
  discountType: 'percent' | 'fixed';
  value: number;
  minSpend: number;
  description: string;
  descriptionBn?: string;
  image?: string;
}

export interface ShippingAddress {
  fullName: string;
  phone: string;
  email: string;
  division: string;
  district: string;
  thana: string;
  streetAddress: string;
  postalCode: string;
  deliveryInstructions?: string;
}

export interface Order {
  id: string;
  /** Human-friendly order number (ORD-...) generated by the backend. */
  orderNumber: string;
  items: CartItem[];
  shippingAddress: ShippingAddress;
  deliveryMethod: 'standard' | 'express' | 'pickup' | 'inside_dhaka' | 'sub_dhaka' | 'outside_dhaka';
  pickupStore?: string;
  paymentMethod: 'bkash' | 'nagad' | 'card' | 'cod';
  subtotal: number;
  discount: number;
  shippingFee: number;
  couponApplied?: Coupon;
  total: number;
  /** Mirrors the backend order lifecycle — pending is the default for new
   *  orders; cancelled/returned/refunded are kept so those orders can be
   *  displayed in history and tracking too. */
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'out_for_delivery' | 'delivered' | 'cancelled' | 'returned' | 'refunded';
  createdAt: string;
  trackingCode: string;
  estimatedDelivery: string;
  /* ── Fields mirrored from the backend order (Phase 2+). All optional so
   *  existing storefront code keeps compiling whether or not the server
   *  returned them. ── */
  customerAddress?: Record<string, unknown>;
  source?: 'storefront' | 'pos' | string;
  isPos?: boolean;
  paidAmount?: number;
  dueAmount?: number;
  invoiceNumber?: string | null;
  paymentStatus?: string;
  deliveryStatus?: string;
  packagingStatus?: string;
  internalNotes?: string | null;
}

export type CurrencyMode = 'BDT' | 'USD';
